In [1]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
import numpy as np

## Note

- Nei grafici gli errori sono a caso
- Mancano i fattori geometrici

In [11]:
#prendo path per tutti uguale
DATA_FILE = Path('Data') / 'dead_zones.csv'
if not DATA_FILE.exists():
    for p in Path.cwd().parents:
        candidate = p / 'Data' / 'dead_zones.csv'
        if candidate.exists():
            DATA_FILE = candidate
            break
df = pd.read_csv(DATA_FILE, sep = r',', header = 0, engine='python') #skiprow=21

display(df)

,ordine[TtB],p_distanza[cm],g_distanza[cm],m_distanza[cm],p_count,pm_doppie,gm_doppie,pg_doppie,pgm_triple,tempo[min]
0,mpg,0.0,0.0,0.0,9321.0,7198.0,5882.0,NaN,5784.0,5.0
1,mpg,15.0,0.0,0.0,9478.0,6597.0,5907.0,NaN,4995.0,5.0
2,mpg,30.0,0.0,0.0,9288.0,5363.0,5877.0,NaN,3743.0,5.0
3,mpg,45.0,0.0,0.0,9194.0,4068.0,5908.0,NaN,2503.0,5.0
4,mpg,60.0,0.0,0.0,9472.0,2761.0,6146.0,NaN,1468.0,5.0
5,mpg,75.0,0.0,0.0,9597.0,1402.0,5896.0,NaN,362.0,5.0
6,mgp,0.0,0.0,0.0,9405.0,5926.0,7188.0,NaN,5787.0,5.0
7,mgp,0.0,15.0,0.0,9300.0,5992.0,6504.0,NaN,4996.0,5.0
8,mgp,0.0,30.0,0.0,9370.0,6024.0,5371.0,NaN,3755.0,5.0
9,mgp,0.0,45.0,0.0,9127.0,5954.0,4039.0,NaN,2540.0,5.0
10,mgp,0.0,60.0,0.0,9440.0,6074.0,2632.0,NaN,1418.0,5.0
11,mgp,0.0,75.0,0.0,9554.0,6082.0,1231.0,NaN,323.0,5.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_P = df[df['ordine[TtB]'] == 'mpg']
df_G = df[df['ordine[TtB]'] == 'mgp']
df_M = df[df['ordine[TtB]'] == 'pgm']

display( df_P )

,ordine[TtB],p_distanza[cm],g_distanza[cm],m_distanza[cm],p_count,pm_doppie,gm_doppie,pg_doppie,pgm_triple,tempo[min]
0,mpg,0.0,0.0,0.0,9321.0,7198.0,5882.0,NaN,5784.0,5.0
1,mpg,15.0,0.0,0.0,9478.0,6597.0,5907.0,NaN,4995.0,5.0
2,mpg,30.0,0.0,0.0,9288.0,5363.0,5877.0,NaN,3743.0,5.0
3,mpg,45.0,0.0,0.0,9194.0,4068.0,5908.0,NaN,2503.0,5.0
4,mpg,60.0,0.0,0.0,9472.0,2761.0,6146.0,NaN,1468.0,5.0
5,mpg,75.0,0.0,0.0,9597.0,1402.0,5896.0,NaN,362.0,5.0

# Efficiency

In [14]:
fig = go.Figure()

fig.add_trace( go.Scatter( x = df_P['p_distanza[cm]'] , y = ((df_P[' pgm_triple'])/(df_P[' gm_doppie'])) , mode = 'markers' , name = 'p_efficiency' , error_y = dict( type='data' , array=0.1*np.ones_like(df_P['p_distanza[cm]']) , visible = True)))


fig.add_trace( go.Scatter( x = df_G['g_distanza[cm]'] , y = ((df_G[' pgm_triple'])/(df_G[' pm_doppie'])) , mode = 'markers' , name = 'g_efficiency' , error_y = dict( type='data' , array=0.1*np.ones_like(df_G['g_distanza[cm]']) , visible = True)))


fig.update_xaxes( title_text = 'distanza[cm]')
fig.update_yaxes( title_text = 'rate triple/doppie')
fig.show()

# Giunone