In [17]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
import numpy as np

## Note

- Nei grafici gli errori sono a caso
- Mancano i fattori geometrici

In [18]:
default_dir = str(Path(".").absolute()).split("/Lab-muons")[0]+"/Lab-muons/"
universal_dir = lambda path: default_dir + path

DATA_PATH = universal_dir("Data/calibration/dead_zones.csv")
SIM_PATH = universal_dir("simulazioni/bolde/muons/muon_distribution_simulation_results.csv")

data = pd.read_csv(DATA_PATH, sep=",", header=0)
sim = pd.read_csv(SIM_PATH , sep=",", header=0)
display(data)
display(sim)

,ordine[TtB],p_distanza[cm],g_distanza[cm],m_distanza[cm],p_count,pm_doppie,gm_doppie,pg_doppie,pgm_triple,tempo[min]
0,mpg,0,0,0,9321,7198,5882,NaN,5784,5.0
1,mpg,15,0,0,9478,6597,5907,NaN,4995,5.0
2,mpg,30,0,0,9288,5363,5877,NaN,3743,5.0
3,mpg,45,0,0,9194,4068,5908,NaN,2503,5.0
4,mpg,60,0,0,9472,2761,6146,NaN,1468,5.0
5,mpg,75,0,0,9597,1402,5896,NaN,362,5.0
6,mgp,0,0,0,9405,5926,7188,NaN,5787,5.0
7,mgp,0,15,0,9300,5992,6504,NaN,4996,5.0
8,mgp,0,30,0,9370,6024,5371,NaN,3755,5.0
9,mgp,0,45,0,9127,5954,4039,NaN,2540,5.0
10,mgp,0,60,0,9440,6074,2632,NaN,1418,5.0
11,mgp,0,75,0,9554,6082,1231,NaN,323,5.0
12,gmp,0,0,0,9179,0,6029,4189.0,4104,NaN
13,gmp,0,0,15,8800,0,5752,4294.0,3871,NaN
14,gmp,0,0,30,9197,0,4074,4093.0,2668,NaN
15,gmp,0,0,45,8212,0,2707,3839.0,1546,NaN
16,gmp,0,0,60,8285,0,1527,3773.0,710,NaN
17,gmp,0,0,75,8108,0,550,3961.0,118,NaN

,configuration,Tx,Ty,Tz,Mx,My,Mz,Bx,By,Bz,doppie,triple,flag
0,m p/g g/p,0,0,12.8,0,0,8.4,0,0,0,409465,250033,761670
1,m p/g g/p,0,0,12.8,15,0,8.4,0,0,0,394573,224085,803034
2,m p/g g/p,0,0,12.8,30,0,8.4,0,0,0,325407,177790,821516
3,m p/g g/p,0,0,12.8,45,0,8.4,0,0,0,245370,123092,826694
4,m p/g g/p,0,0,12.8,60,0,8.4,0,0,0,160108,65804,828189
5,m p/g g/p,0,0,12.8,75,0,8.4,0,0,0,65733,8939,827309
6,p m g,0,0,23.0,0,0,12.8,0,0,0,195414,85431,817186
7,p m g,0,0,23.0,15,0,12.8,0,0,0,200666,78199,833354
8,p m g,0,0,23.0,30,0,12.8,0,0,0,166312,59514,817848
9,p m g,0,0,23.0,45,0,12.8,0,0,0,126266,38691,795614
10,p m g,0,0,23.0,60,0,12.8,0,0,0,85552,17781,772451
11,p m g,0,0,23.0,75,0,12.8,0,0,0,43375,1087,739009
12,p m g,0,0,25.3,0,0,12.8,0,0,0,152330,69862,769892
13,p m g,0,0,25.3,15,0,12.8,0,0,0,159888,63742,784311
14,p m g,0,0,25.3,30,0,12.8,0,0,0,136041,49150,764343
15,p m g,0,0,25.3,45,0,12.8,0,0,0,104343,31274,738385
16,p m g,0,0,25.3,60,0,12.8,0,0,0,72305,14156,711133
17,p m g,0,0,25.3,75,0,12.8,0,0,0,39723,720,672365

In [19]:
df_P = data[data['ordine[TtB]'] == 'mpg']
df_G = data[data['ordine[TtB]'] == 'mgp']
df_M = data[data['ordine[TtB]'] == 'gmp']

display( df_M )

,ordine[TtB],p_distanza[cm],g_distanza[cm],m_distanza[cm],p_count,pm_doppie,gm_doppie,pg_doppie,pgm_triple,tempo[min]
12,gmp,0,0,0,9179,0,6029,4189.0,4104,NaN
13,gmp,0,0,15,8800,0,5752,4294.0,3871,NaN
14,gmp,0,0,30,9197,0,4074,4093.0,2668,NaN
15,gmp,0,0,45,8212,0,2707,3839.0,1546,NaN
16,gmp,0,0,60,8285,0,1527,3773.0,710,NaN
17,gmp,0,0,75,8108,0,550,3961.0,118,NaN

# Misure

In [20]:
fig = go.Figure()

fig.add_trace( go.Scatter( x = df_P['p_distanza[cm]'] , y = ((df_P[' pgm_triple'])/(df_P[' gm_doppie'])) , mode = 'markers' , name = 'p_efficiency' , error_y = dict( type='data' , array=0.1*np.ones_like(df_P['p_distanza[cm]']) , visible = True)))


fig.add_trace( go.Scatter( x = df_G['g_distanza[cm]'] , y = ((df_G[' pgm_triple'])/(df_G[' pm_doppie'])) , mode = 'markers' , name = 'g_efficiency' , error_y = dict( type='data' , array=0.1*np.ones_like(df_G['g_distanza[cm]']) , visible = True)))

fig.add_trace( go.Scatter( x = df_M['m_distanza[cm]'] , y = ((df_M[' pgm_triple'])/(df_M[' pg_doppie'])) , mode = 'markers' , name = 'g_efficiency' , error_y = dict( type='data' , array=0.1*np.ones_like(df_M['m_distanza[cm]']) , visible = True)))


fig.update_xaxes( title_text = 'distanza[cm]')
fig.update_yaxes( title_text = 'rate triple/doppie')
fig.show()

# Simulazione

In [21]:
sim_P = sim[sim['configuration'] == 'm p/g g/p']
sim_G = sim[sim['configuration'] == 'm p/g g/p']
sim_M = sim[sim['configuration'] == 'p m g']

display(sim_P)
display(sim_M)

,configuration,Tx,Ty,Tz,Mx,My,Mz,Bx,By,Bz,doppie,triple,flag
0,m p/g g/p,0,0,12.8,0,0,8.4,0,0,0,409465,250033,761670
1,m p/g g/p,0,0,12.8,15,0,8.4,0,0,0,394573,224085,803034
2,m p/g g/p,0,0,12.8,30,0,8.4,0,0,0,325407,177790,821516
3,m p/g g/p,0,0,12.8,45,0,8.4,0,0,0,245370,123092,826694
4,m p/g g/p,0,0,12.8,60,0,8.4,0,0,0,160108,65804,828189
5,m p/g g/p,0,0,12.8,75,0,8.4,0,0,0,65733,8939,827309

,configuration,Tx,Ty,Tz,Mx,My,Mz,Bx,By,Bz,doppie,triple,flag
6,p m g,0,0,23.0,0,0,12.8,0,0,0,195414,85431,817186
7,p m g,0,0,23.0,15,0,12.8,0,0,0,200666,78199,833354
8,p m g,0,0,23.0,30,0,12.8,0,0,0,166312,59514,817848
9,p m g,0,0,23.0,45,0,12.8,0,0,0,126266,38691,795614
10,p m g,0,0,23.0,60,0,12.8,0,0,0,85552,17781,772451
11,p m g,0,0,23.0,75,0,12.8,0,0,0,43375,1087,739009
12,p m g,0,0,25.3,0,0,12.8,0,0,0,152330,69862,769892
13,p m g,0,0,25.3,15,0,12.8,0,0,0,159888,63742,784311
14,p m g,0,0,25.3,30,0,12.8,0,0,0,136041,49150,764343
15,p m g,0,0,25.3,45,0,12.8,0,0,0,104343,31274,738385
16,p m g,0,0,25.3,60,0,12.8,0,0,0,72305,14156,711133
17,p m g,0,0,25.3,75,0,12.8,0,0,0,39723,720,672365

In [ ]:
fig = go.Figure()

fig.add_trace( go.Scatter( x = sim_P['Mx'] , y = ((sim_P['triple'])/(sim_P[' doppie'])) , mode = 'markers' , name = 'p_sim_efficiency' , error_y = dict( type='data' , array=0.1*np.ones_like(sim_P['Mx']) , visible = True)))


fig.add_trace( go.Scatter( x = sim_M['Mx'] , y = ((sim_M['triple'])/(sim_M[' doppie'])) , mode = 'markers' , name = 'M_sim_efficiency' , error_y = dict( type='data' , array=0.1*np.ones_like(sim_M['Mx']) , visible = True)))

fig.add_trace( go.Scatter( x = sim_G['Mx'] , y = ((sim_G['triple'])/(sim_G[' doppie'])) , mode = 'markers' , name = 'g_sim_efficiency' , error_y = dict( type='data' , array=0.1*np.ones_like(sim_G['Mx']) , visible = True)))


fig.update_xaxes( title_text = 'distanza[cm]')
fig.update_yaxes( title_text = 'rate triple/doppie')
fig.show()

Index(['configuration', 'Tx ', ' Ty ', ' Tz', 'Mx ', ' My ', ' Mz', 'Bx ',
       ' By ', ' Bz', 'doppie', 'triple', 'flag'],
      dtype='object')

KeyError: ' triple'